<?php /** @var $block \AlpineCommerce\StoreLocator\Block\Adminhtml\Store\Listing */ ?>
<div class="page-main-actions">
    <div class="page-actions">
        <a class="action-primary" href="<?= $block->escapeUrl($block->getUrl('*/*/edit')) ?>">
            <span><?= $block->escapeHtml(__('Add New Store')) ?></span>
        </a>
    </div>
</div>
<table class="data-grid">
    <thead>
        <tr>
            <th class="data-grid-th"><span><?= $block->escapeHtml(__('Name')) ?></span></th>
            <th class="data-grid-th"><span><?= $block->escapeHtml(__('Source Code')) ?></span></th>
            <th class="data-grid-th"><span><?= $block->escapeHtml(__('City')) ?></span></th>
            <th class="data-grid-th"><span><?= $block->escapeHtml(__('Status')) ?></span></th>
            <th class="data-grid-th"><span><?= $block->escapeHtml(__('Action')) ?></span></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($block->getStores() as $store): ?>
        <tr>
            <td><?= $block->escapeHtml($store->getName()) ?></td>
            <td><?= $block->escapeHtml($store->getSourceCode()) ?></td>
            <td><?= $block->escapeHtml($store->getCity()) ?></td>
            <td><?= $block->escapeHtml($store->getIsActive() ? __('Active') : __('Inactive')) ?></td>
            <td><a href="<?= $block->escapeUrl($block->getUrl('*/*/edit', ['id' => $store->getId()])) ?>"><?= $block->escapeHtml(__('Edit')) ?></a></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
