[program:alpinecommerce_autoinvoice]
command=php /home/cartware/magento2/bin/magento queue:consumers:start alpincommerce_autoinvoice_async --max-messages=100
autostart=true
autorestart=true
user=www-data
numprocs=1
process_name=%(program_name)s
redirect_stderr=true
stdout_logfile=/var/log/magento/consumers/autoinvoice.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/magento/consumers/autoinvoice_err.log

[program:alpinecommerce_partialinvoice]
command=php /home/cartware/magento2/bin/magento queue:consumers:start alpincommerce_partialinvoice_async --max-messages=100
autostart=true
autorestart=true
user=www-data
numprocs=1
process_name=%(program_name)s
redirect_stderr=true
stdout_logfile=/var/log/magento/consumers/partialinvoice.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/magento/consumers/partialinvoice_err.log

[program:alpinecommerce_creditmemo]
command=php /home/cartware/magento2/bin/magento queue:consumers:start alpincommerce_creditmemo_async --max-messages=100
autostart=true
autorestart=true
user=www-data
numprocs=1
process_name=%(program_name)s
redirect_stderr=true
stdout_logfile=/var/log/magento/consumers/creditmemo.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/magento/consumers/creditmemo_err.log

[program:alpinecommerce_customercare_vip]
command=php /home/cartware/magento2/bin/magento queue:consumers:start alpincommerce_customercare_vip_async --max-messages=100
autostart=true
autorestart=true
user=www-data
numprocs=1
process_name=%(program_name)s
redirect_stderr=true
stdout_logfile=/var/log/magento/consumers/customercare_vip.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stderr_logfile=/var/log/magento/consumers/customercare_vip_err.log
