<?php
/** @var \Cartware\LegalPages\Block\Listing $block */
$pages = $block->getPages();
?>
<?php if ($pages): ?>
    <div class="cartware-legal-list">
        <?php foreach ($pages as $page): ?>
            <div class="cartware-legal-item">
                <h2 class="cartware-legal-title">
                    <a href="<?= $block->escapeUrl($block->getPageUrl($page)) ?>">
                        <?= $block->escapeHtml($page->getTitle()) ?>
                    </a>
                </h2>
                <div class="cartware-legal-type">
                    <?= $block->escapeHtml($page->getType()) ?>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
<?php else: ?>
    <p><?= $block->escapeHtml(__('No legal pages yet.')) ?></p>
<?php endif; ?>
