<?php
/** @var $block AlpineCommerce\ProductLabels\Block\Adminhtml\Label\Edit */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?= /* @noEscape */ $block->getFormInitScripts() ?>
<?php if ($block->getButtonsHtml('toolbar')): ?>
    <div class="page-main-actions">
        <div class="page-actions">
            <div class="page-actions-buttons">
                <?= $block->getButtonsHtml('toolbar') ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?= $block->getChildHtml('form') ?>
<?php $scriptString = <<<script
require([
    'jquery',
    'mage/mage'
], function($){

    $('#edit_form').mage('form').mage('validation', {
        validationUrl: '{$block->escapeJs($block->getValidationUrl())}',
        highlight: function(element) {
            $(element).trigger('highlight.validate');
        }
    });
});

script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?= /* @noEscape */ $block->getFormScripts() ?>
