<?php
/** @var $block AlpineCommerce\ProductLabels\Block\Adminhtml\Label\Edit */
/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
?>
<?= /* @noEscape */ $block->getFormInitScripts() ?>
<?php if ($block->getButtonsHtml('toolbar')): ?>
    <div class="page-main-actions">
        <div class="page-actions">
            <div class="page-actions-buttons">
                <?= $block->getButtonsHtml('toolbar') ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php $editFormInit = json_encode(['AlpineCommerce_ProductLabels/js/label/edit' => ['validationUrl' => $block->getValidationUrl()]]); ?>
<div data-mage-init='<?= /* @noEscape */ $editFormInit ?>'>
    <?= $block->getChildHtml('form') ?>
</div>
<?= /* @noEscape */ $block->getFormScripts() ?>
