<?php
/** @var \Cartware\LoyaltyProgram\Block\Customer\Balance $block */
?>
<div class="block block-loyalty-balance">
    <div class="block-title">
        <strong><?= $block->escapeHtml(__('My loyalty points')) ?></strong>
    </div>
    <div class="block-content">
        <p class="loyalty-balance">
            <?= $block->escapeHtml(__('Your current balance is: %1 points', $block->getBalance())) ?>
        </p>
    </div>
</div>
